# 系统参数
port: 7890                        # HTTP代理端口
socks-port: 7891                  # SOCKS代理端口
redir-port: 7892                  # 透明代理端口（for Linux or MacOS）不能更改
mixed-port: 7893                  # 集成端口，http与socks
#authentication:                   # 验证
#  - "user:user"                 # http与socks的账号跟密码，推荐使用
allow-lan: true                   # 允许局域网连接
mode: Script                      # Rule or Script    # 工作模式（有Global全局，Rule规则，Direct直连,Script脚本）
log-level: info                   # 日志级别（info / warning / error / debug / silent）
ipv6: false                       # 假
external-controller: 0.0.0.0:9090 # 外部控制面板监听端口
external-ui: dashboard            # 外部控制面板仪表板
secret: ""                        # dashboard面板的密码，同时也是tracing的密码
interface-name: eth_n            # ip a 查看接口名称，确认一致 
profile:                          # 描述
  store-selected: true            # 策略组选择缓存开关，打开后可以保存策略组选择，重启不会回复默认
  tracing: true                   # tracing开关，必须打开才能对接tracing
# 实验性功能
experimental:
  ignore-resolve-fail: true
# TUN设置
tun:
  enable: true         
  stack: gvisor
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
    - 8.8.8.8:53
    - 8.8.8.8:53
# DNS设置  
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5352         # DNS监听端口!!!clash下，此处不能改，切记!!!!
  # DNS解析模式（redir-host # or fake-ip），这里重点解释一下：
  # redir-host为真实IP模式，需要设置nameserver（国内）和fallback（国外）两组DNS，当设备发起DNS请求，CLASH会同时向两组里面所有服务器发起请求，然后首先拿nameserver中最快返回的结果去匹配规则，使用GEOIP判断此IP的所属区域，如果属于国内（CN）或保留地址则直接响应给客户端，其他情况则把fallback中的结果响应给客户端
  # fake-ip则相反，当clash收到请求，会直接返回一个198.18.0.1/16的假IP给设备，同时 Clash 继续解析域名规则和 IP 规则，而且如果 Clash DNS 匹配到了域名规则、则不需要向上游 DNS 请求，Clash 已经可以直接将连接发给代理服务器，节省了 Clash DNS 向上游 DNS 请求解析
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip         # 理论上来说，fake-ip具有更好的响应速度跟抗污染能力（主要还得看规则）。由于灯塔提前分流了国内外流量，国内流量不经过clash，所以选择fake-ip可以得到更好的效果，当然，还是得看规则完不完整。有需要返回真实IP的可以选择redir-host，老实说两种DNS模式在实际体验中差别不大
  fake-ip-range: 198.19.0.1/16   # ip范围
  use-hosts: true                # 开启
  fake-ip-filter:                # fake-ip白名单，对于有需要返回真实IP又想用fake-ip的，可参照以下格式把域名加进去
    - msftconnecttest.com
    - "*.msftconnecttest.com"
    - msftncsi.com
    - "*.msftncsi.com"
    - '.lan'
    - localhost.ptlogin2.qq.com    
    - '.srv.nintendo.net'   
    - '.stun.playstation.net'   
    - 'xbox.*.microsoft.com'    
    - '.xboxlive.com'
  nameserver:                    # DNS服务器（国内），此处建议只填一个速度最快的DNS就可以了
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 223.6.6.6
    - 180.76.76.76
    - 1.2.4.8
# 以下就是代理，代理集（需机场支持），策略组设置。请自己观察，注意之间的对应关系!
# 代理集设置    
proxy-providers:
  🇭🇰 香港:                   # 代理集名称
    type: http                   # 代理集类型，有http（网络地址）跟file（本地）两种格式
    path: ./🇭🇰 香港.yaml     # 代理集本地路径
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=香港
    interval: 28800             # 自动检测时间，单位为秒，意思就是每28800更新一次
    health-check:                # 状态检测
      enable: true               # 开启
      url: http://cp.cloudflare.com/generate_204  # 检测地址，每600秒代理集里面的节点向检测地址做一次连通性测试
      interval: 300              # 自动检测时间，单位为秒
  🇰🇷 韩国:
    type: http
    path: ./🇰🇷 韩国.yaml
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=韩国
    interval: 28800
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  🇺🇸 美国:
    type: http
    path: ./🇺🇸 美国.yaml
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=美国
    interval: 28800
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300 
  🇯🇵 日本:
    type: http
    path: ./🇯🇵 日本.yaml
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=日本
    interval: 28800
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300          
  🇸🇬 新加坡:
    type: http
    path: ./🇸🇬 新加坡.yaml
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=新加坡
    interval: 28800
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300   
  🇨🇳 台湾:
    type: http
    path: ./🇨🇳 台湾.yaml
    url: https://dler.cloud/subscribe/token?protocols=ss&list=clash&match=台湾
    interval: 28800
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 600          
# 策略组
proxy-groups:
  - name: 📶 带宽测速
    type: select
    proxies:
      - 📡 直连国内
    use:  
      - 🇭🇰 香港                      #引用（代理集文件）                          
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本 
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
  - name: 🌏 谷歌服务
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本 
      - 🇸🇬 新加坡
      - 🇨🇳 台湾 
      - 📡 直连国内    
  - name: 💬 即时通讯
    type: select
    proxies:
      - 🇺🇸 美国
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇯🇵 日本 
      - 🇸🇬 新加坡
      - 🇨🇳 台湾 
      - 📡 直连国内  
  - name: 🎦 Netflix
    type: select
    proxies:
      - 🇸🇬 新加坡
      - 🇯🇵 日本
      - 🇨🇳 台湾
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 📡 直连国内  
  - name: ▶️ Youtube
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
      - 📡 直连国内  
  - name: 📺 港澳台区
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
      - 📡 直连国内  
  - name: 🎞 Disney
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
      - 📡 直连国内  
  - name: 🎞 国际媒体
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
      - 📡 直连国内  
  - name: 🌍 国际互联
    type: select
    proxies:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
      - 📡 直连国内     
  - name: 🎥 国内媒体
    type: select
    proxies:
      - 📡 直连国内
      - 🌍 国际互联
  - name: 📧 微软服务
    type: select
    proxies:    
      - 🌍 国际互联
      - 📡 直连国内
  - name: 📱 苹果服务
    type: select
    proxies: 
      - 📡 直连国内
      - 🌍 国际互联
  - name: 🎮 游戏平台
    type: select
    proxies:
      - 📡 直连国内    
      - 🌍 国际互联
  - name: ⛔️ 拦截广告
    type: select
    proxies:
      - 🚫 拦截阻断
      - 📡 直连国内
  - name: 🐠 漏网之鱼
    type: select
    proxies:
      - 🌍 国际互联
      - 📡 直连国内    
  - name: 🚫 拦截阻断
    type: select
    proxies:
      - REJECT 
  - name: 📡 直连国内
    type: select
    proxies:
      - DIRECT
#  - name: 🎮 游戏加速
#    type: select
#    use:   
#      - 🇭🇰 香港                      #引用（代理集文件）
#      - 🇰🇷 韩国
#      - 🇺🇸 美国
#      - 🇯🇵 日本 
#      - 🇸🇬 新加坡
#      - 🇨🇳 台湾
#    proxies:
#      - 📡 直连国内    
  - name: 🤟 手动选择
    type: select
    use:
      - 🇭🇰 香港                      #引用（代理集文件）
      - 🇰🇷 韩国
      - 🇺🇸 美国
      - 🇯🇵 日本
      - 🇸🇬 新加坡
      - 🇨🇳 台湾
  - name: 🇰🇷 韩国
    type: url-test
    use:
      - 🇰🇷 韩国
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300
  - name: 🇭🇰 香港
    type: url-test
    use:
      - 🇭🇰 香港
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300
  - name: 🇺🇸 美国
    type: url-test
    use:
      - 🇺🇸 美国
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300
  - name: 🇯🇵 日本
    type: url-test
    use:
      - 🇯🇵 日本
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300   
  - name: 🇨🇳 台湾
    type: url-test
    use:
      - 🇨🇳 台湾
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300     
  - name: 🇸🇬 新加坡
    type: url-test
    use:
      - 🇸🇬 新加坡
    url: http://cp.cloudflare.com/generate_204
    tolerance: 10
    interval: 300       
# clash有几种策略，url-test自动测速，select手动选择，select主备切换，loadbalance轮询均衡，relay中继模式，每个都有他的优劣
# url-test自动测速: 自动测速，我用的最多，每隔一段时间，节点自动向测速点发起连接测速，然后自动选择一个延迟最低的，但这个不是本地到节点，而是节点到测速点.
# select手动选择: 手动选择，顾名思义，手动，不会自动切换.
# select主备切换: 主备切换，节点先发起测速，然后选择第一个可用的节点，一定时间内在测速，如果选择的节点挂了，就顺位换，不挂就继续用，但不考虑延迟.
# loadbalance轮询均衡: 轮训均衡，跟负载均衡差不多，但没什么用.
# relay中继模式: 中继模式，就是可以自定义多个节点的中继行为 
#规则集
rule-providers:
## > 去广告
  AdBlock1:                                   # 规则集文件名
    type: http                                # 规则集文件类型（HTTP=在线下载；File=本地导入）
    behavior: classical                       # 行为域
    path: ./ruleset/广告拦截/AdBlock1.list     # 规则集在线下载保存地址或本地文件导入地址
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e5%b9%bf%e5%91%8a%e6%8b%a6%e6%88%aa/AdBlock1.list  #规则集文件下载地址
    interval: 43200                           # 规则集文件自动更新间隔
  AdBlock2:
    type: http
    behavior: classical
    path: ./ruleset/广告拦截/AdBlock2.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e5%b9%bf%e5%91%8a%e6%8b%a6%e6%88%aa/AdBlock2.list
    interval: 43200
  AdBlock3:
    type: http
    behavior: classical
    path: ./ruleset/广告拦截/AdBlock3.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e5%b9%bf%e5%91%8a%e6%8b%a6%e6%88%aa/AdBlock3.list
    interval: 43200
  AdBlock4:
    type: http
    behavior: classical
    path: ./ruleset/广告拦截/AdBlock4.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA/AdBlock4.list
    interval: 43200
  AdBlock5:
    type: http
    behavior: classical
    path: ./ruleset/广告拦截/AdBlock5.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e5%b9%bf%e5%91%8a%e6%8b%a6%e6%88%aa/AdBlock5.list
    interval: 43200
## > 媒体服务
  # > 油管
  YouTube:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/YouTube.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/YouTube.list
    interval: 43200
  # > 奈飞
  Netflix:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/Netflix.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/Netflix.list
    interval: 43200
  # > 迪士尼+
  Disney:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/Disney.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/Disney.list
    interval: 43200
  # > HBO
  HBO:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/HBO.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/HBO.list
    interval: 43200
  # > 港澳台媒体
  HMTmedia:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/HMTmedia.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/HMTmedia.list
    interval: 43200
  # > 油管音乐   
  YoutubeMusic:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/YoutubeMusic.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/YoutubeMusic.list
    interval: 43200
  # > Apple TV
  AppleTV:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/AppleTV.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e5%aa%92%e4%bd%93%e6%9c%8d%e5%8a%a1/AppleTV.list
    interval: 43200
  # > 其余国际流媒体
  GlobalMedia:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/GlobalMedia.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/GlobalMedia.list
    interval: 43200
  # > 国内流媒体
  Chinesemedia:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/Chinesemedia.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/Chinesemedia.list
    interval: 43200
  # 网易云
  wyy:
    type: http
    behavior: classical
    path: ./ruleset/媒体服务/wyy.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1/wyy.list
    interval: 43200    
## > 网络服务
  # > 苹果服务
  # 苹果API
  AppleAPI:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/AppleAPI.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e7%bd%91%e7%bb%9c%e6%9c%8d%e5%8a%a1/AppleAPI.list
    interval: 43200
  # 苹果CDN
  AppleCDN:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/AppleCDN.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/AppleCDN.list
    interval: 43200
  # 谷歌服务
  Google:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Google.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e7%bd%91%e7%bb%9c%e6%9c%8d%e5%8a%a1/Google.list
    interval: 43200
  # > 谷歌CDN
  GoogleCDN:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/GoogleCDN.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e7%bd%91%e7%bb%9c%e6%9c%8d%e5%8a%a1/GoogleCDN.list
    interval: 43200
  # 微软服务
  Microsoft:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Microsoft.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Microsoft.list
    interval: 43200
  # > 微软CDN
  MicrosoftCDN:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/MicrosoftCDN.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/MicrosoftCDN.list
    interval: 43200
  # 数字货币
  Digital:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Digital.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Digital.list
    interval: 43200    
  # Paypal
  Paypal:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Paypal.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Paypal.list
    interval: 43200
  # Speedtest
  Speedtest:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Speedtest.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Speedtest.list
    interval: 43200
  # 即时通讯（TG,KAKAO,LINE....)
  Telegram:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Telegram.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Telegram.list
    interval: 43200
  # 游戏平台（Steam,xbox,PS,战网）
  gameline:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/gameline.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/gameline.list
    interval: 43200
  # > 回国线路 
  Domestic:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Domestic.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Domestic.list
    interval: 43200
  Lan:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Lan.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E7%BD%91%E7%BB%9C%E6%9C%8D%E5%8A%A1/Lan.list
    interval: 43200
  # > 国际互联
  Proxy:
    type: http
    behavior: classical
    path: ./ruleset/网络服务/Proxy.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%e7%bd%91%e7%bb%9c%e6%9c%8d%e5%8a%a1/Proxy.list
    interval: 43200
## > 黑白名单
  # > 黑名单
  Black:
    type: http
    behavior: classical
    path: ./ruleset/黑白名单/Black.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E9%BB%91%E7%99%BD%E5%90%8D%E5%8D%95/Black.list
    interval: 43200
  # > 白名单
  White:
    type: http
    behavior: classical
    path: ./ruleset/黑白名单/White.list
    url: https://git.o8.cx/https://raw.githubusercontent.com/clash1step/rule-provider/master/%E9%BB%91%E7%99%BD%E5%90%8D%E5%8D%95/White.list
    interval: 43200
# Script匹配模式
script:
    code: |
    
        def main(ctx, metadata):
        ## >> 自定义变量
            # 游戏主机策略               
            #SrcIP = ctx.resolve_ip(metadata["src_ip"])
            #if SrcIP == "10.10.10.14":
                #if metadata["network"] == "udp":
                    #ctx.log('[Script] matched SrcIP')
                    #return "🎮 游戏加速"
                #return "🌍 国际互联"
                
            # 广告拦截策略
            ad_action = {
                "Speedtest": "📶 带宽测速",
                "AdBlock1": "⛔️ 拦截广告",
                "AdBlock2": "⛔️ 拦截广告",
                "AdBlock3": "⛔️ 拦截广告",
                "AdBlock4": "⛔️ 拦截广告",
                "AdBlock5": "⛔️ 拦截广告"
                }
            ad_rule = ["Speedtest","AdBlock1", "AdBlock2", "AdBlock3", "AdBlock4", "AdBlock5"]
            for ad_name in ad_rule:
                if ctx.rule_providers[ad_name].match(metadata):
                    ctx.log('[Script] matched %s' % ad_name)
                    return ad_action[ad_name]
                    
            # Plex策略
            #plex_direct = ["+.plex.direct"]
            #plex_tv = ["+.plex.tv"]
            #for hostname in plex_direct:
                #if hostname in metadata["host"]:
                    #ctx.log('[Script] matched %s' % hostname)
                    #return "🏘回家"
            #for hostname in plex_tv:
                #if hostname in metadata["host"]:
                    #ctx.log('[Script] matched %s' % hostname)
                    #return "🌍 国际互联"
          
            # 定义规则集与策略组
            ruleset_action = {
                "Lan": "📡 直连国内",
                "White": "📡 直连国内",
                "Black": "🌍 国际互联",
                "Telegram": "💬 即时通讯",
                "YouTube": "▶️ Youtube",
                "Netflix": "🎦 Netflix",
                "HMTmedia": "📺 港澳台区",
                "Disney": "🎞 Disney",
                "YoutubeMusic": "🎞 国际媒体",
                "HBO": "🎞 国际媒体",
                "AppleTV": "🎞 国际媒体",
                "GlobalMedia": "🎞 国际媒体", 
                "gameline": "🎮 游戏平台",               
                "Digital": "🌍 国际互联",
                "Paypal": "🌍 国际互联",
                "Proxy": "🌍 国际互联",
                "wyy": "🎥 国内媒体",
                "Chinesemedia": "🎥 国内媒体",
                "AppleAPI": "📱 苹果服务",
                "Google": "🌏 谷歌服务",
                "GoogleCDN": "🌏 谷歌服务",
                "Microsoft": "📧 微软服务",
                "AppleCDN": "📡 直连国内",                  
                "MicrosoftCDN": "📡 直连国内",            
                "Domestic": "📡 直连国内"
                }
            name_rule = ["Lan","White","Black","Telegram","YouTube","Netflix","HMTmedia","Disney","YoutubeMusic","HBO","AppleTV","GlobalMedia","gameline","Google","Digital","Paypal","Proxy","wyy","Chinesemedia","AppleAPI","GoogleCDN","Microsoft","AppleCDN","MicrosoftCDN","Domestic"]
            # 策略组规则
            for rule_name in name_rule:
                if ctx.rule_providers[rule_name].match(metadata):
                    ctx.log('[Script] matched %s' % rule_name)
                    return ruleset_action[rule_name]              
            # 漏网之鱼
            return "🐠 漏网之鱼"